---
- name: "update yum packages."
  become: true
  yum:
    update_cache: true

- name: "upgrade packages"
  become: true
  yum:
    name: "*"
    state: latest

- name: Install Node Source Repository
  become: true
  yum:
    name: https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm
    state: present
  async: 2000
  poll: 0

- name: Install Node.js
  become: true
  yum:
    name: nodejs
    state: present
    extra_args: "--setopt=nodesource-nodejs.module_hotfixes=1"
  async: 2000
  poll: 0


- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present




