---
- name: "update dnf packages."
  become: true
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Install Node Source Repository
  become: true
  ansible.builtin.dnf:
    name: https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm
    state: present
  async: 2000
  poll: 0

- name: Install Node.js
  become: true
  ansible.builtin.dnf:
    name: nodejs
    state: present
    extra_args: "--setopt=nodesource-nodejs.module_hotfixes=1"
  async: 2000
  poll: 0

- name: "install node dependencies"
  become: true
  ansible.builtin.dnf:
    name:
      - npm # TODO: additional steps required before installing this
    state: latest
    update_cache: true

- name: "install pm2"
  become: true
  ansible.builtin.dnf:
    name: pm2
    global: true
    production: true
    state: present




